#!/bin/python3

import os
import sys

#
# Complete the timeConversion function below.
#
def timeConversion(s):
    h, m, s = map(str,s.split(':'))
    seconds=s[:2]
    am_pm=s[2:]
    if am_pm=="PM":
        if h=="12":
            pass
        else:
            h=int(h)+12
            
    elif am_pm=="AM":
        if h=='12':
            h='00'
       

    new_time=str(h)+":"+m+":"+seconds
    return new_time
    


if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)
    
    f.write(result + '\n')

    f.close()
